version: '3.4'

services:
  nginx:
    depends_on:
      - php
    image: nginx:1.21-alpine
    volumes:
      - ./.docker/nginx/templates:/etc/nginx/templates:ro
      - ./public:/usr/src/public:ro
    environment:
      DOCUMENT_ROOT: /usr/src/public
      LISTEN_PORT: 80
      UPSTREAM_FPM_SERVER: php:9000
      NGINX_CLIENT_MAX_BODY_SIZE: ${NGINX_CLIENT_MAX_BODY_SIZE:-20M}
    ports:
      - "8090:80"

  db:
    image: mariadb:10.8.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ludothek
      MYSQL_USER: ludothek
      MYSQL_PASSWORD: ludothek
    ports:
      - "6033:3306"
    volumes:
      - data:/var/lib/mysql:rw,cached

  php:
    build:
      target: development
      context: .docker/php
      args:
        MYUID: 501
        MYGID: 501
    image: pattypur1980/php_for_symfony:latest
    volumes:
      - ./backend:/usr/src:rw,cached
      - var:/usr/src/var:rw,cached
    environment:
      XDEBUG_MODE: 'off'
      XDEBUG_CLIENT_HOST: host.docker.internal
      XDEBUG_TRIGGER: PHPSTORM
      PHP_XDEBUG_MODE: debug
      PHP_XDEBUG_CLIENT_HOST: host.docker.internal
      PHP_XDEBUG_TRIGGER: PHPSTORM
      PHP_IDE_CONFIG: serverName=localhost
      PHP_POST_MAX_SIZE: 21M
      PHP_UPLOAD_MAX_FILESIZE: 20M

  node:
    image: node:16.20.0-alpine3.17
    command: npm run dev
    working_dir: /usr/app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/app:rw,cached

volumes:
  var:
  data:


